apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: app-5-dev
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app-5
  template:
    metadata:
      labels:
        app: dotnet-app-5
    spec:
      containers:
        - name: dotnet-app-5
          image: dokkaushik/dotnet-app-5:15646f05b47934bf6b55da6e5830bd98174d05a2
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
          #readinessProbe:
          #  httpGet:
          #    path: /health
          #    port: 5000
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          #livenessProbe:
          #  httpGet:
          #    path: /health
          #    port: 5000
          #  initialDelaySeconds: 10
          #  periodSeconds: 20
